import type { Lab } from '../../domain/curriculum/types';
import { md, mcq, numeric, explain } from '../helpers';

export const labActivities = [
  // ---- Lab 1: Bloch sphere ----
  mcq({ id: 'lab-bloch-q1', owner: 'lab-bloch', role: 'practice', diff: 1, objs: ['B1.1'], tags: ['relative-phase', 'global-phase'],
    prompt: md`In the lab set $\theta=90^\circ$ and sweep $\varphi$ from $0^\circ$ to $360^\circ$. How does the $Z$-basis probability $P(0)$ change?`,
    hints: ['Read the $Z$-basis bar while moving the $\\varphi$ slider.', 'The amplitude moduli $|\\alpha|,|\\beta|$ do not depend on $\\varphi$.'],
    choices: [['It does not change: $\\varphi$ is invisible to a $Z$ measurement', 'Correct: $P(0)=\\cos^2(\\theta/2)$ is independent of $\\varphi$. But the $X$ and $Y$ probabilities do change.', true], ['It follows $\\cos^2\\varphi$', 'That describes the $X$-basis probability, not $Z$.', false, 'basis-confusion'], ['It drops to 0 at $\\varphi=180^\\circ$', 'At $\\theta=90^\\circ$ the $Z$ probabilities are $1/2$ for all $\\varphi$.'], ['It depends on the global phase slider', 'The global phase slider changes nothing observable.']],
    fb: { correct: 'Relative phase is invisible in the basis where the amplitudes were defined, and visible in conjugate bases.', incorrect: 'Watch which bars move.', solutionSteps: ['$P(0)=|\\alpha|^2=\\cos^2(\\theta/2)$.', '$\\varphi$ appears only in the phase of $\\beta$.'] } }),
  numeric({ id: 'lab-bloch-q2', owner: 'lab-bloch', role: 'practice', diff: 1, objs: ['B1.2'], tags: ['bloch-sphere'], value: 1, tol: 1e-6,
    prompt: md`Set $\theta=90^\circ$, $\varphi=90^\circ$. Read the Bloch vector. What is $\langle Y\rangle$?`,
    hints: ['$\\langle Y\\rangle=\\sin\\theta\\sin\\varphi$.', '$\\sin90^\\circ\\sin90^\\circ$.'],
    wrong: [[0, 'That would be at $\\varphi=0$ or $180^\\circ$. Check your $\\varphi$ value.']],
    fb: { correct: 'The state is $|{+i}\\rangle$ and sits at $+y$.', incorrect: 'Use $\\langle Y\\rangle=\\sin\\theta\\sin\\varphi$ and compare with the readout.', solutionSteps: ['$\\langle Y\\rangle=\\sin90^\\circ\\sin90^\\circ=1$.'] } }),
  explain({ id: 'lab-bloch-q3', owner: 'lab-bloch', role: 'practice', diff: 2, objs: ['B1.1'], tags: ['global-phase', 'relative-phase'], reflection: true,
    prompt: 'Reflection. Using the lab, describe what changed and what did not when you (a) applied a global phase and (b) changed $\\varphi$. Which probabilities moved?',
    rubric: ['Reports that the global phase changed the amplitudes\' phases but no probability in any basis.', md`Reports that changing $\varphi$ left the $Z$ probabilities fixed but moved the $X$ and/or $Y$ probabilities.`, 'Connects the observation to relative versus global phase.'],
    min: 2, model: 'A global phase multiplied both amplitudes by the same factor and every probability stayed the same. Changing $\\varphi$ left $P(0)$ and $P(1)$ unchanged but moved the $X$ and $Y$ basis probabilities because $\\varphi$ is the relative phase.',
    hints: ['Compare the three probability bars before and after each change.', 'Which change keeps the Bloch vector fixed?'],
    fb: { correct: 'Reflection recorded.', incorrect: 'Re-run the lab and note which bars move.', solutionSteps: ['Global phase: Bloch vector fixed.', 'Relative phase: Bloch vector rotates about $z$.'] } }),
  // ---- Lab 2: Bell ----
  numeric({ id: 'lab-bell-q1', owner: 'lab-bell', role: 'practice', diff: 1, objs: ['B4.2'], tags: ['purity', 'bell-state'], value: 0.5, tol: 1e-4,
    prompt: md`Build $|\Phi^+\rangle$ with $H$ on qubit 0 then CNOT. What is the purity of the reduced state of qubit 0 shown in the lab?`,
    hints: ['Look at the reduced density matrix panel.', 'It should be $I/2$.'],
    wrong: [[1, 'Purity 1 would mean qubit 0 is in a pure state, i.e. unentangled.']],
    fb: { correct: '$\\mathrm{tr}(I/2)^2=1/2$: maximally mixed.', incorrect: 'Read the reduced matrix and compute $\\mathrm{tr}\\rho^2$.', solutionSteps: ['$\\rho_A=I/2$.', '$\\mathrm{tr}\\rho_A^2=1/4+1/4=1/2$.'] } }),
  numeric({ id: 'lab-bell-q2', owner: 'lab-bell', role: 'practice', diff: 2, objs: ['B4.1'], tags: ['bell-state', 'relative-phase'], value: -1, tol: 1e-4,
    prompt: md`Modify your circuit to prepare $|\Phi^-\rangle=(|00\rangle-|11\rangle)/\sqrt2$ (add a $Z$ gate). What is $\langle XX\rangle$ in the correlations panel?`,
    hints: ['Which gate flips the relative sign of $|11\\rangle$?', '$\\langle XX\\rangle$ flips sign relative to $|\\Phi^+\\rangle$.'],
    wrong: [[1, 'That is $\\langle XX\\rangle$ for $|\\Phi^+\\rangle$. The extra $Z$ changes the relative phase and flips it.']],
    fb: { correct: '$\\langle XX\\rangle=-1$ for $|\\Phi^-\\rangle$ while $\\langle ZZ\\rangle=+1$ is unchanged.', incorrect: 'Add Z after the CNOT and read the panel.', solutionSteps: ['$XX|\\Phi^-\\rangle=-|\\Phi^-\\rangle$.', 'So $\\langle XX\\rangle=-1$.'] } }),
  explain({ id: 'lab-bell-q3', owner: 'lab-bell', role: 'practice', diff: 3, objs: ['B4.3'], tags: ['no-signalling', 'bell-state'], reflection: true,
    prompt: 'Reflection. In the lab each qubit alone looks like a fair coin, yet the joint counts are perfectly correlated. Explain both observations and why this does not allow signalling.',
    rubric: [md`Local marginals are random because the reduced state is $I/2$.`, 'Joint outcomes are correlated because of the entangled state (and appear in more than one basis).', 'Correlations are only visible after comparing records; no choice of Alice changes Bob\'s marginal.'],
    min: 2, model: 'The reduced state of each qubit is I/2, so its outcomes are 50/50 in any basis. The pair state has ZZ and XX correlations, so joint records match. Comparing records requires classical communication; Bob\'s marginal never depends on what Alice does, so no message is sent.',
    hints: ['Use the reduced density matrix panel and the counts table.', 'What would Bob see without Alice\'s data?'],
    fb: { correct: 'Reflection recorded.', incorrect: 'Revisit the reduced-state panel and the counts.', solutionSteps: ['Marginals: $\\rho=I/2$.', 'Joint: correlated.', 'No signalling: marginals independent of the other party\'s action.'] } }),
  // ---- Lab 3: Noise ----
  numeric({ id: 'lab-noise-q1', owner: 'lab-noise', role: 'practice', diff: 1, objs: ['B6.2'], tags: ['bloch-channels', 'purity'], value: 0.5, tol: 1e-3,
    prompt: md`Choose $|{+}\rangle$ and the phase-flip channel. Set $p=0.5$. What is the purity?`,
    hints: ['At $p=0.5$ the equatorial components vanish.', 'The state becomes $I/2$.'],
    wrong: [[1, 'The lab plot shows purity falling with $p$; check the value at $p=0.5$.']],
    fb: { correct: 'At $p=0.5$ the Bloch vector length is $|1-2p|=0$: fully dephased, purity $1/2$.', incorrect: 'Read the purity curve at $p=0.5$.', solutionSteps: ['$x=(1-2p)=0$.', 'Purity $=(1+0)/2=0.5$.'] } }),
  mcq({ id: 'lab-noise-q2', owner: 'lab-noise', role: 'practice', diff: 2, objs: ['B6.3'], tags: ['amplitude-damping'],
    prompt: md`Set amplitude damping to $\gamma=1$ for several different initial states. What Bloch vector do you always end with?`,
    hints: ['Try $|1\\rangle$ and $|{+}\\rangle$ and compare.', 'Think of full energy relaxation.'],
    choices: [[md`$(0,0,+1)$, i.e. $|0\rangle$`, 'Correct: complete relaxation to the ground-like state $|0\\rangle$ regardless of start.', true], [md`$(0,0,0)$, the maximally mixed state`, 'That is the fixed point of depolarizing noise, not amplitude damping.', false, 'damping-is-symmetric'], [md`The initial state unchanged`, 'At $\\gamma=1$ the channel is maximally strong.'], [md`$(0,0,-1)$, i.e. $|1\rangle$`, 'Amplitude damping moves population from $|1\\rangle$ to $|0\\rangle$ in this convention.']],
    fb: { correct: 'Amplitude damping has fixed point $|0\\rangle$ (non-unital).', incorrect: 'Run the lab with two different initial states.', solutionSteps: ['$K_0=\\mathrm{diag}(1,0)$, $K_1=|0\\rangle\\langle1|$ at $\\gamma=1$.', 'Any $\\rho\\to|0\\rangle\\langle0|$.'] } }),
  explain({ id: 'lab-noise-q3', owner: 'lab-noise', role: 'practice', diff: 3, objs: ['B6.3'], tags: ['dephasing', 'amplitude-damping'], reflection: true,
    prompt: 'Reflection. Compare how phase flip and amplitude damping change $z$, the equatorial components and the purity of $|{+}\\rangle$ in the lab.',
    rubric: [md`Phase flip leaves $z$ fixed and shrinks $x,y$.`, md`Amplitude damping changes $z$ toward $+1$ and also shrinks $x,y$ (by $\sqrt{1-\gamma}$).`, 'Notes purity decreases in both cases (and can partially recover for amplitude damping as the state approaches a pure fixed point).'],
    min: 2, model: 'Phase flip changes only the coherences: x and y shrink by (1-2p) while z stays constant. Amplitude damping shrinks x and y by sqrt(1-gamma) and moves z toward +1; purity first drops and then rises again as the state approaches |0>.',
    hints: ['Watch the Bloch coordinate plots separately.', 'Which channel has a pure fixed point?'],
    fb: { correct: 'Reflection recorded.', incorrect: 'Compare the plotted curves.', solutionSteps: ['Dephasing: coherences only.', 'Relaxation: populations and coherences.'] } }),
  // ---- Lab 4: Physics ----
  numeric({ id: 'lab-physics-q1', owner: 'lab-physics', role: 'practice', diff: 2, objs: ['D1.3'], tags: ['units', 'pauli-hamiltonian'], value: 4.136, tol: 0.01,
    prompt: md`A spin has $H/\hbar=\tfrac{\omega}{2}Z$ with $\omega=2\pi\ \mathrm{rad/\mu s}$ (a $1\ \mathrm{MHz}$ transition). Using the lab's unit panel, what is the energy splitting $\hbar\omega$ in **neV**?`,
    hints: ['$\\hbar\\omega=h\\nu$ with $\\nu=1$ MHz.', '$h=6.62607\\times10^{-34}$ J s and $1\\ \\mathrm{eV}=1.602177\\times10^{-19}$ J.', '$h\\nu=6.626\\times10^{-28}$ J $\\approx4.136\\times10^{-9}$ eV.'],
    wrong: [[0.658, 'That is $\\hbar\\cdot1\\ \\mathrm{rad/\\mu s}$ in neV. Here $\\omega=2\\pi$ rad/$\\mu$s, a factor $2\\pi$ larger.', 0.01]],
    fb: { correct: '$h\\times1\\,\\mathrm{MHz}\\approx4.136$ neV. Nuclear Zeeman splittings are tiny compared with thermal energy at room temperature — hence hyperpolarisation tricks in NMR.', incorrect: 'Convert $\\omega$ to SI: $E=\\hbar\\omega$ in joules, then to eV.', solutionSteps: ['$\\omega=2\\pi\\times10^6\\ \\mathrm{s^{-1}}$.', '$E=\\hbar\\omega=1.0546\\times10^{-34}\\times6.283\\times10^6\\approx6.626\\times10^{-28}$ J.', '$E/e=4.136\\times10^{-9}$ eV $=4.136$ neV.'] } }),
  mcq({ id: 'lab-physics-q2', owner: 'lab-physics', role: 'practice', diff: 2, objs: ['D3.1', 'D3.2'], tags: ['trotter'],
    prompt: md`In the error-versus-steps table for a non-commuting Hamiltonian, you double the number of first-order Trotter steps. About how does the operator-norm error change?`,
    hints: ['First-order formulas have error $O(t^2/n)$ for $n$ steps.', 'The log-log slope shown in the lab is near $-1$.'],
    choices: [['It roughly halves', 'Correct: error $\\propto1/n$ (slope $\\approx-1$). Second order falls roughly four-fold.', true], ['It falls by a factor of about 4', 'That is second-order behaviour (slope $\\approx-2$).', false, 'order-confusion'], ['It does not change', 'More steps means smaller step size and smaller error, until floating-point limits.'], ['It doubles', 'More steps reduce the error but increase circuit depth.']],
    fb: { correct: 'First order: error $\\sim1/n$; second order: $\\sim1/n^2$.', incorrect: 'Read the fitted slope in the lab.', solutionSteps: ['First-order error per unit time $\\propto t^2\\|[A,B]\\|/n$.', 'Doubling $n$ halves it.'] } }),
  explain({ id: 'lab-physics-q3', owner: 'lab-physics', role: 'practice', diff: 3, objs: ['D3.2', 'D3.3'], tags: ['trotter', 'pauli-hamiltonian'], reflection: true,
    prompt: 'Reflection. When is a Trotter product formula exact, what do you pay to make it more accurate, and why is the exact-diagonalisation baseline limited?',
    rubric: ['Says Trotter is exact when the terms commute (the lab\'s commuting preset shows ~0 error).', 'Says more steps or higher order reduce error but increase circuit depth/gate count.', 'Says exact diagonalisation needs a $2^n\\times2^n$ matrix, so memory/time grow exponentially with the number of spins.'],
    min: 2, model: 'If all terms commute, exp(-i sum H_k t) = product of exp(-i H_k t), so Trotterisation is exact. Otherwise the error is governed by commutators; reducing it needs more steps (deeper circuits) or a higher-order formula (more gates per step). Exact diagonalisation stores and diagonalises a 2^n x 2^n matrix, which becomes infeasible beyond a few tens of spins.',
    hints: ['Try the commuting-terms preset in the lab.', 'Count how the number of exponentials grows with steps.'],
    fb: { correct: 'Reflection recorded.', incorrect: 'Re-run the commuting vs non-commuting presets.', solutionSteps: ['Commuting terms: exact.', 'Non-commuting: error from commutators.', 'Exact diagonalisation scales as $2^n$.'] } }),
];

export const labs: Lab[] = [
  {
    id: 'lab-bloch', moduleId: 'B1', title: 'State vector and Bloch sphere', estimatedMinutes: 25,
    summary: 'Construct single-qubit states from angles, vary relative and global phase, and compare measurement probabilities in the Z, X and Y bases.',
    physicsMeaning: 'The Bloch vector is the direction along which a spin-1/2 has a definite spin component. Relative phase rotates it about z and is visible only in conjugate bases; global phase is invisible.',
    objectives: ['Predict Z, X and Y measurement probabilities from the Bloch angles.', 'Show that a global phase changes nothing observable while the relative phase does.'],
    objectiveIds: ['B1.1', 'B1.2'],
    instructions: ['Set θ and φ with the sliders or pick a preset state.', 'Predict the three probability bars before checking them.', 'Apply the global-phase slider and confirm that nothing observable moves.', 'Apply gates (H, S, X, …) and watch the vector rotate.'],
    assumptions: ['Ideal, noiseless single qubit; exact probabilities (no shot noise).', 'Convention: |ψ⟩ = cos(θ/2)|0⟩ + e^{iφ} sin(θ/2)|1⟩; Bloch vector is (⟨X⟩, ⟨Y⟩, ⟨Z⟩).', 'Drawing is an orthographic projection with a fixed viewing tilt; numbers are always shown beside it.'],
    activityIds: ['lab-bloch-q1', 'lab-bloch-q2', 'lab-bloch-q3'], prerequisiteModuleIds: ['B1'],
  },
  {
    id: 'lab-bell', moduleId: 'B4', title: 'Bell-state lab', estimatedMinutes: 30,
    summary: 'Build a two-qubit circuit, compute its statevector, reduced density matrix, correlators and a CHSH value, and sample seeded measurement shots.',
    physicsMeaning: 'The Bell pair is a pure joint state whose subsystems are maximally mixed. Local results are random; joint results are correlated in several bases, and the CHSH value exceeds the classical bound of 2 without any signalling.',
    objectives: ['Construct Bell states with H, CNOT and Pauli gates.', 'Compute and interpret reduced states and correlators.', 'Explain random local outcomes with correlated joint outcomes.'],
    objectiveIds: ['B4.1', 'B4.2', 'B4.3'],
    instructions: ['Start from the Φ+ preset (H on qubit 0, CNOT 0→1) or add gates yourself.', 'Read the amplitudes, the reduced state of qubit 0 and its purity and entropy.', 'Sample shots with a fixed seed and compare the marginals with the joint counts.', 'Change the circuit (for example add Z or X) and watch ⟨ZZ⟩, ⟨XX⟩ and CHSH.'],
    assumptions: ['Ideal gates and ideal projective measurement; shot noise comes only from finite sampling with a seeded generator.', 'Qubit 0 is the leftmost/most significant qubit; CNOT(0,1) has control 0 and target 1.', 'CHSH uses a₀=Z, a₁=X on qubit 0 and b₀,₁=(Z±X)/√2 on qubit 1; it is not an experiment and ignores loopholes.'],
    activityIds: ['lab-bell-q1', 'lab-bell-q2', 'lab-bell-q3'], prerequisiteModuleIds: ['B4'],
  },
  {
    id: 'lab-noise', moduleId: 'B6', title: 'Noise lab', estimatedMinutes: 30,
    summary: 'Apply bit-flip, phase-flip, depolarizing and amplitude-damping channels to a chosen qubit state and plot Bloch coordinates and purity against noise strength.',
    physicsMeaning: 'Channels contract the Bloch ball: dephasing kills coherence only, amplitude damping also moves population toward |0⟩ (T1-type), depolarizing contracts uniformly.',
    objectives: ['Predict the Bloch-coordinate and purity curves of each channel.', 'Distinguish relaxation from dephasing.'],
    objectiveIds: ['B6.2', 'B6.3'],
    instructions: ['Pick an initial state (|+⟩, |0⟩, |1⟩ or custom angles).', 'Pick a channel and read the x, y, z and purity curves over p ∈ [0, 1].', 'Use "apply n times" to see repeated noise compound.', 'Compare channels at the same strength.'],
    assumptions: ['Single qubit, single-use channels with parameter p or γ; no time dependence or correlated noise.', 'Depolarizing: ρ → (1−p)ρ + pI/2. Amplitude damping drives to |0⟩.', 'Mapping to T1 and T2 is conceptual here (γ = 1 − e^{−t/T1}); no hardware data are used.'],
    activityIds: ['lab-noise-q1', 'lab-noise-q2', 'lab-noise-q3'], prerequisiteModuleIds: ['B6'],
  },
  {
    id: 'lab-physics', moduleId: 'D3', title: 'Physics lab: Hamiltonians, spectra and Trotterisation', estimatedMinutes: 40,
    summary: 'Define a one- or two-spin Hamiltonian from Pauli terms, compute its spectrum and exact time evolution, then compare against first- and second-order product formulas and inspect error versus step count.',
    physicsMeaning: 'The Hamiltonian generates time evolution U = exp(−iHt/ħ). A circuit can only apply it approximately by splitting H into exactly implementable pieces; the error comes from non-commuting terms and trades accuracy against circuit depth.',
    objectives: ['Build a Hamiltonian from Pauli terms and read its spectrum in SI units.', 'Compare exact evolution with Trotter approximations.', 'Interpret error scaling with step size and the exact-diagonalisation baseline.'],
    objectiveIds: ['D1.3', 'D3.1', 'D3.2', 'D3.3'],
    instructions: ['Choose a preset or edit the Pauli terms (coefficients in rad/μs).', 'Read the spectrum, in rad/μs, MHz and neV.', 'Choose an initial state and total time; compare exact and Trotter ⟨Z⟩(t) curves.', 'Inspect the error-versus-steps table and the fitted log-log slope for first and second order.'],
    assumptions: ['ħ = 1 internally; H/ħ is in rad/μs and time in μs. SI conversions: E = ħω, ν = ω/2π.', 'At most 2 qubits (4×4 matrices); exact propagator by scaling-and-squaring matrix exponential.', 'Trotter error is the operator-norm distance between exact and approximate propagators for the chosen total time.', 'This is a numerical illustration, not a resource estimate for real hardware.'],
    activityIds: ['lab-physics-q1', 'lab-physics-q2', 'lab-physics-q3'], prerequisiteModuleIds: ['D1', 'D2', 'C1'],
  },
];
